Add audit logging
PageUpPeopleOrg/pageup-dbt-utils pull request #9
Opened 2019-05-08 07:01 UTC by seanbudd

2019-05-09 00:35 UTC, elexisvenator requested changes

2019-05-09 00:35 UTC, elexisvenator commented on dbt_project.yml
> +  - "{{ pageup_dbt_utils.log_execution_end_event() }}"
put these in the main project instead

2019-05-09 01:53 UTC, seanbudd commented
todo: use the results object in full https://docs.getdbt.com/reference#results

2019-05-13 03:25 UTC, elexisvenator approved these changes

2019-05-13 03:25 UTC, andreissov approved these changes
Good looks to me

2019-05-13 03:39 UTC, merged